stages:
- stage: build
  displayName: Build .NET Project
  jobs:
  - job: dotnetpub
    displayName: Publish .NET Project Artifacts    
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
    - script: dotnet --version
      displayName: Check .NET Version
    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/win --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
      displayName: Publish Windows application
      workingDirectory: src/Phonetic.Speller.Console
    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/linux --self-contained --runtime linux-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
      displayName: Publish Linux application
      workingDirectory: src/Phonetic.Speller.Console
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifact
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: distributions
- stage: publish
  displayName: Publish application
  jobs:
  - job: publish_dockerhub
    displayName: Publish to Docker Hub
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dh_yrollhid
    - task: Docker@2
      displayName: Build Container Image and Push to Docker Hub
      inputs:
        containerRegistry: dh_yrollhid
        repository: yansroll/pspell
        command: buildAndPush
        tags: |
          $(Build.BuildNumber)
          latest
  - job: publish_github
    displayName: Publish to GitHub
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Build Artifact
      inputs:
        buildType: current
        artifactName: distributions
        downloadPath: $(Build.ArtifactStagingDirectory)
    - task: GitHubRelease@0
      displayName: Create GitHub Release
      inputs:
        gitHubConnection: YRollHid
        repositoryName: YRollHid/pspell
        tagSource: manual
        tag: $(Build.BuildNumber)
        assets: $(Build.ArtifactStagingDirectory)/distributions/**/*
