stages:
- stage: push_nuget
  displayName: Push to NuGet
  jobs:
  - job: push_consoleapp
    displayName: Push Console Application as DotNet Tool  
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
    - script: dotnet pack --output pkg
    - task: NuGetCommand@2
      inputs:
        command: push
        feedsToUse: Farm
        packagesToPush: pkg/*.nupkg
  