jobs:
- job: push_nuget
  displayName: Push to NuGet
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      outputDir: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: packages
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '9aaf6d2c-4ab5-4d12-b235-28819cfd56c6/e422179a-a2f2-4b34-af12-1ac748bb6084'
      allowPackageConflicts: true