stages:
- stage: push_nuget
  displayName: Push to NuGet
  jobs:
  - job: push_consoleapp
    displayName: Push Console Application as DotNet Tool  
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
    - task: DotNetCoreCLI@2
      displayName: Package Console Application
      inputs:
        command: pack
        outputDir: $(Build.ArtifactStagingDirectory)
    - task: NuGetCommand@2
      displayName: Push Console Application to NuGet
      inputs:
        command: push
        feedsToUse: Farm
        packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
    - task: PublishBuildArtifacts@1
      displayName: Publish Package Artifacts
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: packages