stages:
- stage: push_nuget
  displayName: Push to NuGet
  jobs:
  - job: push_consoleapp
    displayName: Push Console Application as DotNet Tool  
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 3.1
    - task: DotNetCoreCLI@2
      inputs:
        command: pack
        outputDir: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: packages
    - task: NuGetCommand@2
      inputs:
        command: push
        feedsToUse: Farm
        packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
  