stages:
- stage: push_nuget
  displayName: Push to NuGet
  jobs:
  - job: push_consoleapp
    displayName: Push Console Application as DotNet Tool  
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: 3.1.102
    - task: DotNetCoreCLI@2
      inputs:
        command: pack
        outputDir: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: packages
    - task: NuGetCommand@2
      inputs:
        command: push
        feedsToUse: Farm
        packagesToPush: pkg/*.nupkg
  